version: 2.1

build_jobs: &build_jobs
  jobs:
    - build-amd64
    - build-arm64
    - build-armhf
    - push-manifest:
        requires:
          - build-amd64
          - build-arm64
          - build-armhf

workflows:
  version: 2
  commit:
    <<: *build_jobs
  nightly:
    <<: *build_jobs
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

shared: &shared
  docker:
    - image: docker:18-git
  steps:
    - checkout

    - setup_remote_docker:
        docker_layer_caching: true

    - run:
        name: Install build dependencies.
        command: apk add --upgrade --no-cache bash curl git jq make perl

    - run:
        name: Add dynamic shared vars to env.
        command: .circleci/load_env.sh

    - run:
        name: Build and push Docker image.
        command: |
          source $BASH_ENV
          .circleci/build-image.sh

jobs:
  build-amd64:
    <<: *shared
    environment:
      GOARCH: amd64
      TAG: amd64
      TARGET: amd64
      QEMU_ARCH: amd64
  build-arm64:
    <<: *shared
    environment:
      GOARCH: arm64
      QEMU_ARCH: aarch64
      REGISTRY: jessestuart
      TAG: arm64
      TARGET: arm64v8
  build-armhf:
    <<: *shared
    environment:
      GOARCH: arm
      QEMU_ARCH: arm
      REGISTRY: jessestuart
      TAG: arm
      TARGET: arm32v6

  push-manifest:
    docker:
      - image: docker:stable-git
    environment:
      GITHUB_REPO: minio/mc
      IMAGE: mc
      REGISTRY: jessestuart
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Determine repo version.
          command: |
            apk add --no-cache curl jq
            curl -sL https://api.github.com/repos/${GITHUB_REPO}/releases/latest | jq -r ".tag_name" > ~/VERSION

      - run:
          name: Install manifest-tool, push + verify manifest.
          command: |
            apk update && apk add --upgrade curl jq
            sh .circleci/load_env.sh
            source $BASH_ENV
            sh .circleci/push_manifest.sh

      - run:
          name: Update microbadger metadata.
          command: |
            curl -X POST https://hooks.microbadger.com/images/jessestuart/mc/vOV2w474FXCREXZdkvjIW6FSTpM=
